<?php

namespace App\Http\Resources;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class TreatmentGetFeeViewResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        return [
            'id' => $this->id,
            'createTime' => $this->create_time,
            'modifyTime' => $this->modify_time,
            'creator' => $this->creator,
            'modifier' => $this->modifier,
            'appCreator' => $this->app_creator,
            'appModifier' => $this->app_modifier,
            'isActive' => $this->is_active,
            'isDelete' => $this->is_delete,
            'treatmentCode' => $this->treatment_code,
            'patientId' => $this->patient_id,
            'branchId' => $this->branch_id,
            'isPause' => $this->is_pause,
            'isLockHein' => $this->is_lock_hein,
            'icdCode' => $this->icd_code,
            'icdName' => $this->icd_name,
            'icdSubCode' => $this->icd_sub_code,
            'icdText' => $this->icd_text,
            'feeLockTime' => $this->fee_lock_time,
            'feeLockOrder' => $this->fee_lock_order,
            'feeLockRoomId' => $this->fee_lock_room_id,
            'feeLockDepartmentId' => $this->fee_lock_department_id,
            'inTime' => $this->in_time,
            'inDate' => $this->in_date,
            'outTime' => $this->out_time,
            'hospitalizationReason' => $this->hospitalization_reason,
            'doctorLoginname' => $this->doctor_loginname,
            'doctorUsername' => $this->doctor_username,
            'endLoginname' => $this->end_loginname,
            'endUsername' => $this->end_username,
            'endRoomId' => $this->end_room_id,
            'endDepartmentId' => $this->end_department_id,
            'endCode' => $this->end_code,
            'treatmentDayCount' => $this->treatment_day_count,
            'treatmentResultId' => $this->treatment_result_id,
            'treatmentEndTypeId' => $this->treatment_end_type_id,
            'appointmentTime' => $this->appointment_time,
            'outDate' => $this->out_date,
            'tdlHeinCardNumber' => $this->tdl_hein_card_number,
            'clinicalNote' => $this->clinical_note,
            'tdlFirstExamRoomId' => $this->tdl_first_exam_room_id,
            'tdlTreatmentTypeId' => $this->tdl_treatment_type_id,
            'tdlPatientTypeId' => $this->tdl_patient_type_id,
            'tdlHeinMediOrgCode' => $this->tdl_hein_medi_org_code,
            'tdlHeinMediOrgName' => $this->tdl_hein_medi_org_name,
            'xml4210Url' => $this->xml4210_url,
            'tdlPatientCode' => $this->tdl_patient_code,
            'tdlPatientName' => $this->tdl_patient_name,
            'tdlPatientFirstName' => $this->tdl_patient_first_name,
            'tdlPatientLastName' => $this->tdl_patient_last_name,
            'tdlPatientDob' => $this->tdl_patient_dob,
            'tdlPatientIsHasNotDayDob' => $this->tdl_patient_is_has_not_day_dob,
            'tdlPatientAvatarUrl' => $this->tdl_patient_avatar_url,
            'tdlPatientAddress' => $this->tdl_patient_address,
            'tdlPatientGenderId' => $this->tdl_patient_gender_id,
            'tdlPatientGenderName' => $this->tdl_patient_gender_name,
            'tdlPatientCareerName' => $this->tdl_patient_career_name,
            'tdlPatientDistrictCode' => $this->tdl_patient_district_code,
            'tdlPatientProvinceCode' => $this->tdl_patient_province_code,
            'tdlPatientCommuneCode' => $this->tdl_patient_commune_code,
            'tdlPatientNationalName' => $this->tdl_patient_national_name,
            'appointmentExamRoomIds' => $this->appointment_exam_room_ids,
            'departmentIds' => $this->department_ids,
            'lastDepartmentId' => $this->last_department_id,
            'provisionalDiagnosis' => $this->provisional_diagnosis,
            'tdlPatientPhone' => $this->tdl_patient_phone,
            'isSyncEmr' => $this->is_sync_emr,
            'xml4210Result' => $this->xml4210_result,
            'collinearXml4210Url' => $this->collinear_xml4210_url,
            'collinearXml4210Result' => $this->collinear_xml4210_result,
            'tdlHeinCardFromTime' => $this->tdl_hein_card_from_time,
            'tdlHeinCardToTime' => $this->tdl_hein_card_to_time,
            'appointmentDate' => $this->appointment_date,
            'virInMonth' => $this->vir_in_month,
            'virOutMonth' => $this->vir_out_month,
            'virInYear' => $this->vir_in_year,
            'virOutYear' => $this->vir_out_year,
            'feeLockLoginname' => $this->fee_lock_loginname,
            'feeLockUsername' => $this->fee_lock_username,
            'appointmentExamServiceId' => $this->appointment_exam_service_id,
            'tdlPatientCccdNumber' => $this->tdl_patient_cccd_number,
            'tdlPatientCccdDate' => $this->tdl_patient_cccd_date,
            'tdlPatientRelativeMobile' => $this->tdl_patient_relative_mobile,
            'tdlPatientNationalCode' => $this->tdl_patient_national_code,
            'tdlPatientProvinceName' => $this->tdl_patient_province_name,
            'tdlPatientDistrictName' => $this->tdl_patient_district_name,
            'tdlPatientCommuneName' => $this->tdl_patient_commune_name,
            'isBhytHolded' => $this->is_bhyt_holded,
            'showIcdCode' => $this->show_icd_code,
            'showIcdName' => $this->show_icd_name,
            'showIcdSubCode' => $this->show_icd_sub_code,
            'showIcdText' => $this->show_icd_text,
            'tdlPatientUnsignedName' => $this->tdl_patient_unsigned_name,
            'tdlPatientEthnicName' => $this->tdl_patient_ethnic_name,
            'isTuberculosis' => $this->is_tuberculosis,
            'storeBordereauCode' => $this->store_bordereau_code,
            'heinLockTime' => $this->hein_lock_time,
            'receptionForm' => $this->reception_form,
            'hospitalDirectorLoginname' => $this->hospital_director_loginname,
            'hospitalDirectorUsername' => $this->hospital_director_username,
            'hasCard' => $this->has_card,
            'totalBillAmount' => $this->total_bill_amount,
            'totalBillOtherAmount' => $this->total_bill_other_amount,
            'totalBillTransferAmount' => $this->total_bill_transfer_amount,
            'totalBillExemption' => $this->total_bill_exemption,
            'totalBillFund' => $this->total_bill_fund,
            'totalDepositAmount' => $this->total_deposit_amount,
            'totalRepayAmount' => $this->total_repay_amount,
            'totalPrice' => $this->total_price,
            'totalHeinPrice' => $this->total_hein_price,
            'totalOtherCopaidPrice' => $this->total_other_copaid_price,
            'totalPatientPrice' => $this->total_patient_price,
            'totalDiscount' => $this->total_discount,
            'totalPriceExpend' => $this->total_price_expend,
            'countHeinApproval' => $this->count_hein_approval,
            'totalDebtAmount' => $this->total_debt_amount,
            'totalPatientPriceBhyt' => $this->total_patient_price_bhyt,
            'totalOtherSourcePrice' => $this->total_other_source_price,
            'lastDepositTime' => $this->last_deposit_time,
            'totalServiceDepositAmount' => $this->total_service_deposit_amount,
            'tdlTreatmentTypeCode' => $this->tdl_treatment_type_code,
            'tdlTreatmentTypeName' => $this->tdl_treatment_type_name,
            'heinTreatmentTypeCode' => $this->hein_treatment_type_code,
            'lockingAmount' => $this->locking_amount,
        ];
    }
}
