<?php

return [
    'elastic' => [
        'all_table' => [
            'area',
            'atc',
            'accident_body_part',
            'accident_location',
            'accident_hurt_type',
            'accident_care',
            'awareness',
            'atc_group',
            'age_type',
            'bed_bsty',
            'bed',
            'bed_room',
            'bed_type',
            'bhyt_blacklist',
            'bhyt_param',
            'bhyt_whitelist',
            'bid',
            'bid_type',
            'blood_group',
            'blood_volume',
            'body_part',
            'born_position',
            'branch',
            'cancel_reason',
            'career',
            'career_title',
            'cashier_room',
            'commune',
            'contraindication',
            'data_store',
            'death_within',
            'debate_reason',
            'debate_type',
            'department',
            'diim_type',
            'district',
            'dosage_form',
            'emotionless_method',
            'employee',
            'ethnic',
            'execute_group',
            'execute_role',
            'execute_role_user',
            'execute_room',
            'exe_service_module',
            'exp_mest_reason',
            'exro_room',
            'file_type',
            'film_size',
            'fuex_type',
            'gender',
            'group',
            'group_type',
            'hein_service_type',
            'hospitalize_reason',
            'htu',
            'icd_cm',
            'icd',
            'icd_group',
            'imp_source',
            'interaction_reason',
            'license_class',
            'location_store',
            'machine',
            'manufacturer',
            'material_type',
            'material_type_map',
            'medical_contract',
            'medicine',
            'medicine_group',
            'medicine_line',
            'medicine_paty',
            'medicine_type_acin',
            'medicine_type',
            'medicine_use_form',
            'medi_org',
            'medi_record_type',
            'medi_stock',
            'medi_stock_maty',
            'medi_stock_mety',
            'mema_group',
            'mest_patient_type',
            'mest_room',
            'military_rank',
            'module',
            'module_role',
            'national',
            'other_pay_source',
            'package',
            'packing_type',
            'patient_case',
            'patient_classify',
            'patient_type_allow',
            'patient_type',
            'patient_type_room',
            'position',
            'preparations_blood',
            'priority_type',
            'processing_method',
            'province',
            'pttt_catastrophe',
            'pttt_condition',
            'pttt_group',
            'pttt_method',
            'pttt_table',
            'ration_group',
            'ration_time',
            'reception_room',
            'refectory',
            'relation',
            'religion',
            'role',
            'room',
            'room_group',
            'room_type',
            'sale_profit_cfg',
            'service_condition',
            'service',
            'service_follow',
            'service_group',
            'service_machine',
            'service_paty',
            'service_req_type',
            'service_room',
            'service_type',
            'service_unit',
            'serv_segr',
            'speciality',
            'storage_condition',
            'suim_index',
            'suim_index_unit',
            'supplier',
            'test_index',
            'test_index_group',
            'test_index_unit',
            'test_sample_type',
            'test_type',
            'tran_pati_tech',
            'treatment_end_type',
            'treatment_type',
            'unlimit_reason',
            'vaccine_type',
            'work_place',
        ],
        'error' => [
            'elasticsearch_service' => 'Có lỗi khi thực hiện thao tác với Elastic Search!',
            'build_search_body' => 'Có lỗi khi xây dựng body trong thao tác với Elastic Search!',
            'execute_search' => 'Có lỗi khi thực thi tìm kiếm với Elastic Search!',
            'build_search_query' => 'Có lỗi khi xây dựng query trong thao tác với Elastic Search!',
            'build_highlight' => 'Có lỗi khi xây dựng highlight trong thao tác với Elastic Search!',
            'build_paginate_elastic' => 'Có lỗi khi xây dựng paginate trong thao tác với Elastic Search!',
            'build_sort' => 'Có lỗi khi xây dựng sort trong thao tác với Elastic Search!',
            'build_arr_search_body' => 'Có lỗi khi kết hợp các phần của body trong thao tác với Elastic Search!',
            'build_search' => 'Có lỗi trong lúc tìm kiếm với Elastic Search!',
            'apply_resource' => 'Có lỗi khi điều chỉnh tên trường trả về với Elastic Search!',
            'counting' => 'Có lỗi khi đếm tổng số bản ghi trả về với Elastic Search!',
            'handle_elastic_search_search' => 'Có lỗi khi lấy danh sách Document theo từ khóa với Elastic Search!',
            'handle_elastic_search_get_all' => 'Có lỗi khi lấy danh sách Document với Elastic Search!',
            'handle_elastic_search_get_with_id' => 'Có lỗi khi lấy Document theo id với Elastic Search!',

            'connection' => 'Có lỗi khi kết nối đến Elastic Search!',
            'create_index' => 'Có lỗi khi thực hiện tạo Index!',
            'insert_index' => 'Có lỗi khi thực hiện thêm Document vào Index!',
            'delete_index' => 'Có lỗi khi thực hiện xóa Document trong Index!',
        ]
    ],
    'db_service' => [
        'error' => [
            'apply_resource' => 'Có lỗi khi điều chỉnh tên trường trả về với DB!',
            'transaction' => 'Có lỗi trong Transaction!',
            'accident_body_part' => 'Có lỗi khi thực hiện thao tác với bảng Bộ phận thương tích!',
            'accident_care' => 'Có lỗi khi thực hiện thao tác với bảng Xử lý sau tai nạn!',
            'accident_hurt_type' => 'Có lỗi khi thực hiện thao tác với bảng Nguyên nhân tai nạn!',
            'accident_location' => 'Có lỗi khi thực hiện thao tác với bảng Địa điểm tai nạn!',
            'age_type' => 'Có lỗi khi thực hiện thao tác với bảng Loại tuổi!',
            'area' => 'Có lỗi khi thực hiện thao tác với bảng Khu vực!',
            'atc_group' => 'Có lỗi khi thực hiện thao tác với bảng Nhóm ATC!',
            'awareness' => 'Có lỗi khi thực hiện thao tác với bảng Ý thức!',
            'bed' => 'Có lỗi khi thực hiện thao tác với bảng Giường!',
            'bed_bsty' => 'Có lỗi khi thực hiện thao tác với bảng Giường - Dịch vụ giường!',
            'bed_room' => 'Có lỗi khi thực hiện thao tác với bảng Buồng bệnh!',
            'bed_type' => 'Có lỗi khi thực hiện thao tác với bảng Loại giường!',
            'bhyt_blacklist' => 'Có lỗi khi thực hiện thao tác với bảng Thẻ BHYT không hợp lệ!',
            'bhyt_param' => 'Có lỗi khi thực hiện thao tác với bảng Tham số BHYT!',
            'bhyt_whitelist' => 'Có lỗi khi thực hiện thao tác với bảng Đầu mã thẻ BHYT!',
            'bid_type' => 'Có lỗi khi thực hiện thao tác với bảng Loại thầu!',
            'blood_group' => 'Có lỗi khi thực hiện thao tác với bảng Nhóm máu!',
            'blood_volume' => 'Có lỗi khi thực hiện thao tác với bảng Dung tích túi máu!',
            'body_part' => 'Có lỗi khi thực hiện thao tác với bảng Bộ phận cơ thể!',
            'born_position' => 'Có lỗi khi thực hiện thao tác với bảng Ngôi thai!',
            'branch' => 'Có lỗi khi thực hiện thao tác với bảng Cơ sở/Xã phường!',
            'cancel_reason' => 'Có lỗi khi thực hiện thao tác với bảng Lý do hủy giao dịch!',
            'career' => 'Có lỗi khi thực hiện thao tác với bảng Nghề nghiệp!',
            'career_title' => 'Có lỗi khi thực hiện thao tác với bảng Nghề nghiệp nhân viên!',
            'cashier_room' => 'Có lỗi khi thực hiện thao tác với bảng Phòng thu ngân!',
            'commune' => 'Có lỗi khi thực hiện thao tác với bảng Xã!',
            'contraindication' => 'Có lỗi khi thực hiện thao tác với bảng Chống chỉ định!',
            'data_store' => 'Có lỗi khi thực hiện thao tác với bảng Tủ bệnh án!',
            'death_within' => 'Có lỗi khi thực hiện thao tác với bảng Thời gian tử vong!',
            'debate_reason' => 'Có lỗi khi thực hiện thao tác với bảng Lý do hội chẩn!',
            'debate_type' => 'Có lỗi khi thực hiện thao tác với bảng Loại hội chẩn!',
            'department' => 'Có lỗi khi thực hiện thao tác với bảng Khoa phòng!',
            'diim_type' => 'Có lỗi khi thực hiện thao tác với bảng Loại chẩn đoán hình ảnh!',
            'district' => 'Có lỗi khi thực hiện thao tác với bảng Huyện!',
            'dosage_form' => 'Có lỗi khi thực hiện thao tác với bảng Dạng bào chế!',
            'emotionless_method' => 'Có lỗi khi thực hiện thao tác với bảng Phương pháp vô cảm!',
            'employee' => 'Có lỗi khi thực hiện thao tác với bảng Tài khoản nhân viên!',
            'ethnic' => 'Có lỗi khi thực hiện thao tác với bảng Dân tộc!',
            'execute_group' => 'Có lỗi khi thực hiện thao tác với bảng Nhóm thực hiện!',
            'execute_role' => 'Có lỗi khi thực hiện thao tác với bảng Vai trò thực hiện!',
            'execute_role_user' => 'Có lỗi khi thực hiện thao tác với bảng Tài khoản - Vai trò thực hiện!',
            'execute_room' => 'Có lỗi khi thực hiện thao tác với bảng Phòng khám/cls/pttt!',
            'exe_service_module' => 'Có lỗi khi thực hiện thao tác với bảng Module xử lý dịch vụ!',
            'exp_mest_reason' => 'Có lỗi khi thực hiện thao tác với bảng Lý do xuất!',
            'exro_room' => 'Có lỗi khi thực hiện thao tác với bảng Phòng chỉ định - Phòng thực hiện!',
            'file_type' => 'Có lỗi khi thực hiện thao tác với bảng Loại giấy tờ!',
            'film_size' => 'Có lỗi khi thực hiện thao tác với bảng Cỡ phim!',
            'fuex_type' => 'Có lỗi khi thực hiện thao tác với bảng Loại thăm dò chức năng!',
            'gender' => 'Có lỗi khi thực hiện thao tác với bảng Giới tính!',
            'group' => 'Có lỗi khi thực hiện thao tác với bảng Đơn vị!',
            'hein_service_type' => 'Có lỗi khi thực hiện thao tác với bảng Nhóm dịch vụ BHYT!',
            'hospitalize_reason' => 'Có lỗi khi thực hiện thao tác với bảng Lý do nhập viện!',
            'icd_cm' => 'Có lỗi khi thực hiện thao tác với bảng ICD - CM!',
            'icd' => 'Có lỗi khi thực hiện thao tác với bảng Chẩn đoán!',
            'icd_group' => 'Có lỗi khi thực hiện thao tác với bảng Nhóm ICD!',
            'info_user' => 'Có lỗi khi thực hiện thao tác với bảng Tài khoản nhân viên!',
            'interaction_reason' => 'Có lỗi khi thực hiện thao tác với bảng Lý do kê đơn tương tác!',
            'license_class' => 'Có lỗi khi thực hiện thao tác với bảng Hạng lái xe!',
            'location_store' => 'Có lỗi khi thực hiện thao tác với bảng Vị trí hồ sơ bệnh án!',
            'machine' => 'Có lỗi khi thực hiện thao tác với bảng Máy / Máy cận lâm sàng!',
            'manufacturer' => 'Có lỗi khi thực hiện thao tác với bảng Hãng sản xuất!',
            'material_type' => 'Có lỗi khi thực hiện thao tác với bảng Loại vật tư!',
            'medicine' => 'Có lỗi khi thực hiện thao tác với bảng Thuốc!',
            'medicine_group' => 'Có lỗi khi thực hiện thao tác với bảng Nhóm thuốc!',
            'medicine_line' => 'Có lỗi khi thực hiện thao tác với bảng Dòng thuốc!',
            'medicine_paty' => 'Có lỗi khi thực hiện thao tác với bảng Chính sách giá thuốc!',
            'medicine_type_acin' => 'Có lỗi khi thực hiện thao tác với bảng Loại thuốc - Hoạt chất!',
            'medicine_type' => 'Có lỗi khi thực hiện thao tác với bảng Loại thuốc!',
            'medicine_use_form' => 'Có lỗi khi thực hiện thao tác với bảng Đường dùng thuốc!',
            'medi_org' => 'Có lỗi khi thực hiện thao tác với bảng Cơ sở khám chữa bệnh ban đầu!',
            'medi_record_type' => 'Có lỗi khi thực hiện thao tác với bảng Loại bệnh án!',
            'medi_stock' => 'Có lỗi khi thực hiện thao tác với bảng Kho!',
            'medi_stock_maty' => 'Có lỗi khi thực hiện thao tác với bảng Kho - Loại vật tư!',
            'medi_stock_mety' => 'Có lỗi khi thực hiện thao tác với bảng Kho - Loại thuốc!',
            'mest_patient_type' => 'Có lỗi khi thực hiện thao tác với bảng Kho - Đối tượng!',
            'mest_room' => 'Có lỗi khi thực hiện thao tác với bảng Kho - Phòng!',
            'military_rank' => 'Có lỗi khi thực hiện thao tác với bảng Quân hàm!',
            'module_role' => 'Có lỗi khi thực hiện thao tác với bảng Vai trò - Chức năng!',
            'module' => 'Có lỗi khi thực hiện thao tác với bảng Chức năng!',
            'national' => 'Có lỗi khi thực hiện thao tác với bảng Quốc gia!',
            'other_pay_source' => 'Có lỗi khi thực hiện thao tác với bảng Nguồn chi trả khác!',
            'package' => 'Có lỗi khi thực hiện thao tác với bảng Gói!',
            'patient_case' => 'Có lỗi khi thực hiện thao tác với bảng Trường hợp bệnh!',
            'patient_classify' => 'Có lỗi khi thực hiện thao tác với bảng Phân loại bệnh nhân!',
            'patient_type_allow' => 'Có lỗi khi thực hiện thao tác với bảng Chuyển đổi đối tượng!',
            'patient_type' => 'Có lỗi khi thực hiện thao tác với bảng Đối tượng bệnh nhân!',
            'patient_type_room' => 'Có lỗi khi thực hiện thao tác với bảng Phòng thực hiện - Đối tượng bệnh nhân!',
            'position' => 'Có lỗi khi thực hiện thao tác với bảng Chức vụ!',
            'preparations_blood' => 'Có lỗi khi thực hiện thao tác với bảng Chế phẩm máu!',
            'priority_type' => 'Có lỗi khi thực hiện thao tác với bảng Đối tượng ưu tiên!',
            'processing_method' => 'Có lỗi khi thực hiện thao tác với bảng Phương pháp chế biến!',
            'province' => 'Có lỗi khi thực hiện thao tác với bảng Tỉnh!',
            'pttt_catastrophe' => 'Có lỗi khi thực hiện thao tác với bảng Tai biến PTTT!',
            'pttt_condition' => 'Có lỗi khi thực hiện thao tác với bảng Tình trạng PTTT!',
            'pttt_group' => 'Có lỗi khi thực hiện thao tác với bảng Nhóm PTTT!',
            'pttt_method' => 'Có lỗi khi thực hiện thao tác với bảng Phương pháp PTTT!',
            'pttt_table' => 'Có lỗi khi thực hiện thao tác với bảng Bàn mổ!',
            'ration_group' => 'Có lỗi khi thực hiện thao tác với bảng Nhóm xuất ăn!',
            'ration_time' => 'Có lỗi khi thực hiện thao tác với bảng Bữa ăn!',
            'reception_room' => 'Có lỗi khi thực hiện thao tác với bảng Khu đón tiếp!',
            'refectory' => 'Có lỗi khi thực hiện thao tác với bảng Nhà ăn!',
            'relation' => 'Có lỗi khi thực hiện thao tác với bảng Mối quan hệ!',
            'religion' => 'Có lỗi khi thực hiện thao tác với bảng Tôn giáo!',
            'role' => 'Có lỗi khi thực hiện thao tác với bảng Vai trò!',
            'room' => 'Có lỗi khi thực hiện thao tác với bảng Phòng!',
            'room_group' => 'Có lỗi khi thực hiện thao tác với bảng Nhóm phòng!',
            'room_type' => 'Có lỗi khi thực hiện thao tác với bảng Loại phòng!',
            'sale_profit_cfg' => 'Có lỗi khi thực hiện thao tác với bảng Thiết lập lợi nhuận xuất bán!',
            'service_condition' => 'Có lỗi khi thực hiện thao tác với bảng Điều kiện dịch vụ!',
            'service' => 'Có lỗi khi thực hiện thao tác với bảng Dịch vụ kỹ thuật!',
            'service_follow' => 'Có lỗi khi thực hiện thao tác với bảng Dịch vụ đi kèm!',
            'service_group' => 'Có lỗi khi thực hiện thao tác với bảng Nhóm dịch vụ!',
            'service_machine' => 'Có lỗi khi thực hiện thao tác với bảng Dịch vụ máy!',
            'service_paty' => 'Có lỗi khi thực hiện thao tác với bảng Chính sách giá dịch vụ!',
            'service_req_type' => 'Có lỗi khi thực hiện thao tác với bảng Loại y lệnh!',
            'service_room' => 'Có lỗi khi thực hiện thao tác với bảng Dịch vụ phòng!',
            'service_type' => 'Có lỗi khi thực hiện thao tác với bảng Loại dịch vụ!',
            'service_unit' => 'Có lỗi khi thực hiện thao tác với bảng Đơn vị tính!',
            'serv_segr' => 'Có lỗi khi thực hiện thao tác với bảng Nhóm dịch vụ!',
            'speciality' => 'Có lỗi khi thực hiện thao tác với bảng Chuyên khoa!',
            'suim_index' => 'Có lỗi khi thực hiện thao tác với bảng Chỉ số!',
            'supplier' => 'Có lỗi khi thực hiện thao tác với bảng Nhà cung cấp!',
            'test_index' => 'Có lỗi khi thực hiện thao tác với bảng Chỉ số xét nghiệm!',
            'test_index_unit' => 'Có lỗi khi thực hiện thao tác với bảng Đơn vị tính chỉ số xét nghiệm!',
            'test_sample_type' => 'Có lỗi khi thực hiện thao tác với bảng Loại mẫu bệnh phẩm!',
            'test_type' => 'Có lỗi khi thực hiện thao tác với bảng Loại xét nghiệm!',
            'tran_pati_tech' => 'Có lỗi khi thực hiện thao tác với bảng Lý do chuyển tuyến chuyên môn!',
            'treatment_end_type' => 'Có lỗi khi thực hiện thao tác với bảng Loại ra viện!',
            'treatment_type' => 'Có lỗi khi thực hiện thao tác với bảng Diện điều trị!',
            'unlimit_reason' => 'Có lỗi khi thực hiện thao tác với bảng Lý do mở trần!',
            'work_place' => 'Có lỗi khi thực hiện thao tác với bảng Nơi làm việc!',
            'group_type' => 'Có lỗi khi thực hiện thao tác với bảng Loại đơn vị!',
            'packing_type' => 'Có lỗi khi thực hiện thao tác với bảng Quy cách đóng gói!',
            'material_type_map' => 'Có lỗi khi thực hiện thao tác với bảng Vật tư tương đương!',
            'mema_group' => 'Có lỗi khi thực hiện thao tác với bảng Mema Group!',
            'imp_source' => 'Có lỗi khi thực hiện thao tác với bảng Nguồn nhập!',
            'medical_contract' => 'Có lỗi khi thực hiện thao tác với bảng Hợp đồng dược!',
            'bid' => 'Có lỗi khi thực hiện thao tác với bảng Thầu!',
            'atc' => 'Có lỗi khi thực hiện thao tác với bảng ATC!',
            'storage_condition' => 'Có lỗi khi thực hiện thao tác với bảng Điều kiện bảo quản!',
            'vaccine_type' => 'Có lỗi khi thực hiện thao tác với bảng Loại Vaccine!',
            'htu' => 'Có lỗi khi thực hiện thao tác với bảng Cách dùng thuốc!',
            'suim_index_unit' => 'Có lỗi khi thực hiện thao tác với bảng Đơn vị tính chỉ số siêu âm!',
            'test_index_group' => 'Có lỗi khi thực hiện thao tác với bảng Nhóm chỉ số xét nghiệm!',

        ]
    ]
    
];
