<?php

return [
    'elastic' => [
        'all_table' => [
            'his_area',
            'his_accident_body_part',
            'his_accident_location',
            'his_accident_hurt_type',
            'his_accident_care',
            'his_awareness',
            'his_atc_group',
            'his_age_type',
            'his_bed_bsty',
            'his_bed',
            'his_bed_room',
            'his_bed_type',
            'his_bhyt_blacklist',
            'his_bhyt_param',
            'his_bhyt_whitelist',
            'his_bid_type',
            'his_blood_group',
            'his_blood_volume',
            'his_body_part',
            'his_born_position',
            'his_branch',
            'his_cancel_reason',
            'his_career',
            'his_career_title',
            'his_cashier_room',
            'sda_commune',
            'his_contraindication',
            'his_data_store',
            'his_death_within',
            'his_debate_reason',
            'his_debate_type',
            'his_department',
            'his_diim_type',
            'sda_district',
            'his_dosage_form',
            'his_emotionless_method',
            'his_employee',
            'sda_ethnic',
            'his_execute_group',
            'his_execute_role',
            'his_execute_role_user',
            'his_execute_room',
            'his_exe_service_module',
            'his_exp_mest_reason',
            'his_exro_room',
            'his_file_type',
            'his_film_size',
            'his_fuex_type',
            'his_gender',
            'sda_group',
            'his_hein_service_type',
            'his_hospitalize_reason',
            'his_icd_cm',
            'his_icd',
            'his_icd_group',
            'acs_user',
            'his_interaction_reason',
            'his_license_class',
            'his_location_store',
            'his_machine',
            'his_manufacturer',
            'his_material_type',
            'his_medicine',
            'his_medicine_group',
            'his_medicine_line',
            'his_medicine_paty',
            'his_medicine_type_acin',
            'his_medicine_type',
            'his_medicine_use_form',
            'his_medi_org',
            'his_medi_record_type',
            'his_medi_stock',
            'his_medi_stock_maty',
            'his_medi_stock_mety',
            'his_mest_patient_type',
            'his_mest_room',
            'his_military_rank',
            'acs_module_role',
            'sda_national',
            'his_other_pay_source',
            'his_package',
            'his_patient_case',
            'his_patient_classify',
            'his_patient_type_allow',
            'his_patient_type',
            'his_patient_type_room',
            'his_position',
            'his_preparations_blood',
            'his_priority_type',
            'his_processing_method',
            'sda_province',
            'his_pttt_catastrophe',
            'his_pttt_condition',
            'his_pttt_group',
            'his_pttt_method',
            'his_pttt_table',
            'his_ration_group',
            'his_ration_time',
            'his_reception_room',
            'his_refectory',
            'emr_relation',
            'sda_religion',
            'acs_role',
            'his_room',
            'his_room_group',
            'his_room_type',
            'his_sale_profit_cfg',
            'his_service_condition',
            'his_service',
            'his_service_follow',
            'his_service_group',
            'his_service_machine',
            'his_service_paty',
            'his_service_req_type',
            'his_service_room',
            'his_service_type',
            'his_service_unit',
            'his_serv_segr',
            'his_speciality',
            'his_suim_index',
            'his_supplier',
            'his_test_index',
            'his_test_index_unit',
            'his_test_sample_type',
            'his_test_type',
            'his_tran_pati_tech',
            'his_treatment_end_type',
            'his_treatment_type',
            'his_unlimit_reason',
            'his_work_place',
        ],
        'error' => [
            'elasticsearch_service' => 'Có lỗi khi thực hiện thao tác với Elastic Search!',
            'build_search_body' => 'Có lỗi khi xây dựng body trong thao tác với Elastic Search!',
            'execute_search' => 'Có lỗi khi thực thi tìm kiếm với Elastic Search!',
            'build_search_query' => 'Có lỗi khi xây dựng query trong thao tác với Elastic Search!',
            'build_highlight' => 'Có lỗi khi xây dựng highlight trong thao tác với Elastic Search!',
            'build_paginate_elastic' => 'Có lỗi khi xây dựng paginate trong thao tác với Elastic Search!',
            'build_sort' => 'Có lỗi khi xây dựng sort trong thao tác với Elastic Search!',
            'build_arr_search_body' => 'Có lỗi khi kết hợp các phần của body trong thao tác với Elastic Search!',
            'build_search' => 'Có lỗi trong lúc tìm kiếm với Elastic Search!',
            'apply_resource' => 'Có lỗi khi điều chỉnh tên trường trả về với Elastic Search!',
            'counting' => 'Có lỗi khi đếm tổng số bản ghi trả về với Elastic Search!',
            'handle_elastic_search_search' => 'Có lỗi khi lấy danh sách Document theo từ khóa với Elastic Search!',
            'handle_elastic_search_get_all' => 'Có lỗi khi lấy danh sách Document với Elastic Search!',
            'handle_elastic_search_get_with_id' => 'Có lỗi khi lấy Document theo id với Elastic Search!',

            'connection' => 'Có lỗi khi kết nối đến Elastic Search!',
            'create_index' => 'Có lỗi khi thực hiện tạo Index!',
            'insert_index' => 'Có lỗi khi thực hiện thêm Document vào Index!',
            'delete_index' => 'Có lỗi khi thực hiện xóa Document trong Index!',
        ]
    ],
    'db_service' => [
        'error' => [
            'accident_body_part' => 'Có lỗi khi thực hiện thao tác với bảng Bộ phận thương tích!',
            'accident_care' => 'Có lỗi khi thực hiện thao tác với bảng Xử lý sau tai nạn!',
            'accident_hurt_type' => 'Có lỗi khi thực hiện thao tác với bảng Nguyên nhân tai nạn!',
            'accident_location' => 'Có lỗi khi thực hiện thao tác với bảng Địa điểm tai nạn!',
            'age_type' => 'Có lỗi khi thực hiện thao tác với bảng Loại tuổi!',
            'area' => 'Có lỗi khi thực hiện thao tác với bảng Khu vực!',
            'atc_group' => 'Có lỗi khi thực hiện thao tác với bảng Nhóm ATC!',
            'awareness' => 'Có lỗi khi thực hiện thao tác với bảng Ý thức!',
            'bed' => 'Có lỗi khi thực hiện thao tác với bảng Giường!',
            'bed_bsty' => 'Có lỗi khi thực hiện thao tác với bảng Giường - Dịch vụ giường!',
            'bed_room' => 'Có lỗi khi thực hiện thao tác với bảng Buồng bệnh!',
            'bed_type' => 'Có lỗi khi thực hiện thao tác với bảng Loại giường!',
            'bhyt_blacklist' => 'Có lỗi khi thực hiện thao tác với bảng Thẻ BHYT không hợp lệ!',
            'bhyt_param' => 'Có lỗi khi thực hiện thao tác với bảng Tham số BHYT!',
            'bhyt_whitelist' => 'Có lỗi khi thực hiện thao tác với bảng Đầu mã thẻ BHYT!',
            'bid_type' => 'Có lỗi khi thực hiện thao tác với bảng Loại thầu!',
            'blood_group' => 'Có lỗi khi thực hiện thao tác với bảng Nhóm máu!',
            'blood_volume' => 'Có lỗi khi thực hiện thao tác với bảng Dung tích túi máu!',
            'body_part' => 'Có lỗi khi thực hiện thao tác với bảng Bộ phận cơ thể!',
            'born_position' => 'Có lỗi khi thực hiện thao tác với bảng Ngôi thai!',

        ]
    ]
    
];
