<?php

namespace App\Http\Controllers\BaseControllers;

use App\Events\Cache\DeleteCache;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Redis;

class CacheController extends BaseApiCacheController
{
    public function __construct(Request $request)
    {
        parent::__construct($request); // Gọi constructor của BaseController

    }
    public function clearCache(Request $request)
    {
        // Nếu xóa hết cache
        if (in_array('all', $this->keys) && !$this->tab) {
            // Redis::select(config('database')['redis']['cache']['database']);  // Chuyển về db cache
            Redis::connection('cache')->flushAll();
        }
        // Nếu là voBenhAn
        if ($this->tab == 'voBenhAn') {
            $this->keys =  [
                "setting", //Cache hỗ trợ
                "department",
                "pttt_catastrophe",
                "pttt_condition",
                "pttt_method",
                "service_req_type",
                "service_req_stt",
                "treatment_end_type",
                "emr_cover_type",
                "emr_form",
                "icd",
                "death_cause",
                "death_within",
                "medical_case_cover_list_v_view",
                "treatment_result",
                "user_room_v_view",
                "sere_serv_cls_list_v_view",
                "sere_serv_tein_charts_v_view",
                "treatment_list_v_view",
                "employee",
                "signer",
                "speed_unit",
                "repay_reason",
                "fund",
                "service_paty",
                "service",
                "execute_room",
                'area',
                'atc',
                'accident_body_part',
                'accident_location',
                'accident_hurt_type',
                'accident_care',
                'awareness',
                'atc_group',
                'age_type',
                'bed_bsty',
                'bed',
                'bed_room',
                'bed_type',
                'bhyt_blacklist',
                'bhyt_param',
                'bhyt_whitelist',
                'bid',
                'bid_type',
                'blood_group',
                'blood_volume',
                'body_part',
                'born_position',
                'branch',
                'cancel_reason',
                'career',
                'career_title',
                'cashier_room',
                'commune',
                'contraindication',
                'data_store',
                'death_within',
                'debate_reason',
                'debate_type',
                'diim_type',
                'district',
                'dosage_form',
                'emotionless_method',
                'employee',
                'ethnic',
                'execute_group',
                'execute_role',
                'execute_role_user',
                'execute_room',
                'exe_service_module',
                'exp_mest_reason',
                'exro_room',
                'file_type',
                'film_size',
                'fuex_type',
                'gender',
                'group',
                'group_type',
                'hein_service_type',
                'hospitalize_reason',
                'htu',
                'icd_cm',
                'icd',
                'icd_group',
                'imp_source',
                'interaction_reason',
                'license_class',
                'location_store',
                'machine',
                'manufacturer',
                'material_type',
                'material_type_map',
                'medical_contract',
                'medicine',
                'medicine_group',
                'medicine_line',
                'medicine_paty',
                'medicine_type_acin',
                'medicine_type',
                'medicine_use_form',
                'medi_org',
                'medi_record_type',
                'medi_stock',
                'medi_stock_maty',
                'medi_stock_mety',
                'mema_group',
                'mest_patient_type',
                'mest_room',
                'military_rank',
                'module',
                'module_role',
                'national',
                'other_pay_source',
                'package',
                'packing_type',
                'patient_case',
                'patient_classify',
                'patient_type_allow',
                'patient_type',
                'patient_type_room',
                'pay_form',
                'position',
                'preparations_blood',
                'priority_type',
                'processing_method',
                'province',
                'pttt_group',
                'pttt_table',
                'ration_group',
                'ration_time',
                'reception_room',
                'refectory',
                'relation',
                'religion',
                'role',
                'room',
                'room_group',
                'room_type',
                'sale_profit_cfg',
                'service_condition',
                'service',
                'service_follow',
                'service_group',
                'service_machine',
                'service_paty',
                'service_room',
                'service_type',
                'service_unit',
                'serv_segr',
                'speciality',
                'storage_condition',
                'suim_index',
                'suim_index_unit',
                'supplier',
                'test_index',
                'test_index_group',
                'test_index_unit',
                'test_sample_type',
                'test_type',
                'tran_pati_tech',
                'transaction_type',
                'treatment_type',
                'unlimit_reason',
                'vaccine_type',
                'work_place',
                'emr_cover_type',
                'emr_form',
                'room_v_view',
                'icd_list_v_view',
                'death_cause',
                'treatment_result',
                'tran_pati_form',
                'document_type',
                'service_req_l_view',
                'debate',
                'debate_v_view',
                'user_room_v_view',
                'exp_mest_type',
            ];
        }
        // Nếu xóa theo param
        foreach ($this->keys as $key => $item) {
            event(new DeleteCache($item));
        }
        return returnClearCache();
    }
    public function clearCacheElaticIndexKeyword(Request $request)
    {
        event(new DeleteCache('elastic_index_keyword_' . $request->index));
        return returnClearCache();
    }
}
